### PR TITLE
Use `setup_lfs` action in compare refdata pipeline

### PR DESCRIPTION
**Pull request by atharva-2001**
### :pencil: Description

**Type:** :beetle: `bugfix` :roller_coaster: `infrastructure`

This will make the pre release workflow pass.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Review by andrewfullard — APPROVED** [review]

**Comment by andrewfullard** [comment]
Odd that the action pull from TARDIS is failing due to something in the docs?

**Comment by atharva-2001** [comment]
> Odd that the action pull from TARDIS is failing due to something in the docs?

Yes, that is strange, I'd figure it out and let you know!

**Comment by andrewfullard** [comment]
Is this still relevant?

**Comment by atharva-2001** [comment]
> Is this still relevant?
I don't think so.

**Pull request closed without merging**
